### ISSUE TITLE
deprecation-handling request: drop use of https://install-github.me/

### ISSUE THREAD

**Issue by SKalt** [jozefhajnala/languageserversetup#2]
I ran

```R
install.packages("languageserversetup")
languageserversetup::languageserver_install()
```
Among the output, I noticed the warning:  **"The install-github.me service is deprecated, please stop using it."**  Going to https://install-github.me/ itself gave the message

```
      Do not use this service, it is insecure.
      It is deprecated now, and will be defunct soon.
```

All that seems pretty clear.  See [line 12 of ./R/languageserver)install.R](https://github.com/jozefhajnala/languageserversetup/blob/183c5f7f6277f05cdc4d3237851dc32317e0f20d/R/languageserver_install.R#L12) for the definition of languageserver_install, the function that appears to invoke install-github.me.

**Comment by smurpau** [comment]
I now get the error:
`Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  InternetOpenUrl failed: 'The certificate authority is invalid or incorrect'`

Had to manually force it with 
languageserversetup::languageserver_install(rlsLib = getOption("langserver_library"), strictLibrary = TRUE, fullReinstall = TRUE, fromGitHub = **FALSE**, confirmBeforeInstall = TRUE, dryRun = FALSE)

**Comment by jozefhajnala** [comment]
Thanks for reporting! It should be solved in https://github.com/jozefhajnala/languageserversetup/pull/5.
